### ISSUE TITLE
E-Mail address validation fails for .brussels domain

### ISSUE THREAD

**Issue by AlephAyin** [CASES-LU/Monarc_demo#1]
Hello,

While creating a new user, the address "@xxx.brussels" are rejected.

The validation in ./node_modules/ng_client/views/dialogs/create.user.html is too strict - the allowed length should be extented to at least 8 chars.

Most administrations in the region are moving to this address scheme.

Cheers!

Aleph

**Comment by jfrocha** [comment]
Thanks Aleph
It was fixed. (commit a2ee9d1).
BR
